# Please keep the python- prefix as it is part of our naming convention
service: ${self:custom.prefix}-yourLayerName
frameworkVersion: ">2.0.0"

custom:
  aws:
    account: ${env:AWS_ACCOUNT, '000000000000'}
  schedule: ${file(./myCustomFile.js):schedule.ten}
  v: ${file(./python-version.js):python.version}
  python: ${env:PYTHON, file(./python-version.js):python.version, 'python3.9'}
  prefix: ${env:PYTHON, file(./python-version.js):python.prefix, 'python39'}

provider:
  name: aws
  stage: ${opt:stage, 'layer'}
  region: ${opt:region, 'us-west-2'}
  deploymentBucket:
    name: em-serverless-apps-${self:provider.region}-${self:custom.aws.account}

package:
  exclude:
    - temp/**
    - node_modules/**
    - '*.json'
  include:
    - python/lib/${self:custom.python}

layers:
  lib:
    path: '' # required, path to layer contents on disk
    name: ${self:service}-${self:provider.stage} # Deployed Lambda layer name
    compatibleRuntimes: ${self:custom.python}
    allowedAccounts: # optional, a list of AWS account IDs allowed to access this layer.
      - ${self:custom.aws.account}
    retain: true # optional, false by default. If true, layer versions are not deleted as new ones are created
